/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.lang.reflect.Method;
import java.util.ArrayList;

import com.google.gson.Gson;

public class Main {

    public static void main(String[] args) {

        ArrayList<String> list = new ArrayList<>();
        Method[] stringMethods = String.class.getMethods();
        for (Method method : stringMethods) {
            list.add(method.toString());
        }
        Gson gson = new Gson();
        System.out.println(gson.toJson(list));
    }
}
